[package]
name = "axum-poc"
version = "0.1.0"
edition = "2021"
authors = ["23prime <23.prime.37@gmail.com>"]
rust-version = "1.70.0"


[dependencies]
axum = "0.6.18"
serde = { version = "1.0.164", features = ["derive"] }
tokio = { version = "1.28.2", features = ["full"] }
